# Generated by Django 5.2.7 on 2025-11-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInformativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Página informativa',
                'verbose_name_plural': 'Páginas informativas',
            },
        ),
    ]
