# Generated by Django 5.2.7 on 2025-11-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('transbank', 'Transbank'), ('mercadopago', 'MercadoPago')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de la transacción en la pasarela de pago', max_length=100, null=True),
        ),
    ]
