# Generated by Django 5.2.7 on 2025-11-12 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_estado_pago_pedido_metodo_pago_and_more'),
        ('productos', '0005_producto_precio_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('fallido', 'Fallido')], default='carrito', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.cliente'),
        ),
        migrations.CreateModel(
            name='DatosEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recibe', models.CharField(max_length=150)),
                ('direccion_recibe', models.CharField(max_length=255)),
                ('ciudad_recibe', models.CharField(max_length=100)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_envio', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DatosFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_facturacion', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('direccion_facturacion', models.CharField(max_length=255)),
                ('ciudad_facturacion', models.CharField(max_length=100)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_factura', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente_envio', 'Pendiente envío SII'), ('enviado', 'Enviado SII'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente_envio', max_length=20)),
                ('folio', models.CharField(blank=True, max_length=50)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documento_tributario', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
