# Generated by Django 5.2.7 on 2025-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedido_ciudad_remove_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfactura',
            name='ciudad_facturacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosfactura',
            name='direccion_facturacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datosfactura',
            name='giro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datosfactura',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datosfactura',
            name='rut_facturacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
