# Generated by Django 5.2.7 on 2025-11-12 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='direccion',
            new_name='direccion_usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut_usuario',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_facturacion', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('direccion_facturacion', models.CharField(max_length=255)),
                ('ciudad_facturacion', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_facturacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
