# Generated by Django 5.2.7 on 2025-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='url_proveedor',
            field=models.URLField(blank=True, null=True),
        ),
    ]
