# Generated by Django 5.2.7 on 2025-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_codigo_proveedor_producto_url_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
